### ISSUE TITLE
Authentication: `2.16.0` breaks the `authStateChanges` AsyncStream

### ISSUE THREAD

**Issue by LucasAbijmil** [supabase/supabase-swift#521]
# Bug report
Up to version `2.15.3`, when logging in or signing up with phone number and OTP, the  `authChanges` AsyncStream is sending (as expected) an event containing a session. However, from version `2.16.0` onwards, **this is no longer the case**.

Similarly, when signing out (local or global), no event returning a nil session is sent in the `authChanges` AsyncStream.
I have to restart my application to get the session updated.

The problem also seems to be present on the last two releases (2.17.0 & 2.17.1). 

In order to reproduce the issue as closely as possible, here's my class responsible for managing authentication. As you can see, no logic has been added on top of Supabase, apart from transforming the AsyncStream into a custom one (see below)

## Describe the bug
No event are sent when user is logging in or logging out.

## To Reproduce
```
final class DefaultAuthenticationService: AuthenticationService {
  var state: AsyncStream<AuthenticationState> {
    return client.auth.authStateChanges
      .filter { $0.event == .initialSession || $0.event == .signedIn || $0.event == .signedOut }
      .map {
        print("=======", $0.session)
        return $0.session == nil ? .loggedOut : .loggedIn
      }
      .eraseToStream()
  }
  private let client: SupabaseClient

  init(client: SupabaseClient) {
    self.client = client
  }

  func login(for phoneNumber: String) async throws {
    try await client.auth.signInWithOTP(phone: phoneNumber, shouldCreateUser: false)
  }

  func signUp(for phoneNumber: String) async throws {
    try await client.auth.signInWithOTP(phone: phoneNumber, shouldCreateUser: true)
  }

  func verify(for phoneNumber: String, using code: String) async throws {
    try await client.auth.verifyOTP(phone: phoneNumber, token: code, type: .sms)
  }

  func logout() async throws {
    try await client.auth.signOut(scope: .local)
  }
}
```

## Expected behavior
An event should be sent in the AsyncStream as it was done previously.

## Additional context
As my application is using phone numbers, I'm not able to test this scenario for other authentication types (email, Apple...)

**Comment by grdsdev** [comment]
Hi @LucasAbijmil thanks for reporting this issue, I'll try to reproduce, and come back to you with my findings.

**Comment by grdsdev** [comment]
Version 2.16.0 have no change that could possibly break this feature, 2.16.1 tho has some changes on that part of the code.

Can you confirm it stops working from 2.16.0 up and not 2.16.1?

**Comment by LucasAbijmil** [comment]
Can you confirm it stops working from 2.16.0 up and not 2.16.1?

> Version 2.16.0 have no change that could possibly break this feature, 2.16.1 tho has some changes on that part of the code.
> 
> Can you confirm it stops working from 2.16.0 up and not 2.16.1?

Yes, I can confirm that the problem starts with version `2.16.0` - even though no changes have been made (which I agree is weird). 
Let me know I can help

**Comment by grdsdev** [comment]
I just implemented a phone sign in flow using the 2.16.0 version and auth state changes stream is working fine, check my implementation https://github.com/supabase/supabase-swift/compare/phone-sign-in-issue

Please double check if there isn't a bug in yours implementation.

On the code snippet you provided, the computed state property may be an issue, since it returns a new stream every time it gets accessed.

**Comment by LucasAbijmil** [comment]
I will check and reopen an issue if needed. What is weird is that I've been doing this for several months without any trouble so far. 
Even when using the AsyncStream provided by the SDK (without doing any `filter` / `map` / `eraseToStream`), the issue persists.
