### ISSUE TITLE
Auth session doesn't refresh when using database

### ISSUE THREAD

**Issue by ryansburgoyne** [supabase/supabase-swift#77]
# Bug report

## Describe the bug

If my JWT has expired since I last called `supabaseClient.auth.session`, and I try to execute a command using `supabaseClient.database`, I get an error about the JWT being expired. I have to work around this by calling `_ = supabaseClient.auth.session` before every database call to force it to refresh the token.

## To Reproduce

1. Log in using Supabase Auth
2. Wait for the token to expire
3. Try to perform an operation on a database

## Expected behavior

I would expect the session to automatically be refreshed before attempting the database operation.

## System information

- OS: macOS
- Version of supabase-swift: 0.2.1

**Comment by Pedr0Rocha** [comment]
At some point it was there:
https://github.com/supabase-community/supabase-swift/commit/098cc9390064ac499c1ae3a2e216cc1b3e7b8a09#diff-8ae3298b041e73e9ea309814eeb66aeb229f08265773c84cad2a9e83349ff5caR93

but then it was removed?
https://github.com/supabase-community/supabase-swift/commit/13293398a1d1fe74268c4db37f745c46977262f1#diff-8ae3298b041e73e9ea309814eeb66aeb229f08265773c84cad2a9e83349ff5caL114

**Comment by kurtguenther** [comment]
I too am running into this issue (I get 401 when I restart my app after the JWT expires). I agree with @grsouza that (at least from my read of the GoTrue code) the token should already automatically refresh when `auth.session` is fetched.

https://github.com/supabase-community/gotrue-swift/blob/4bf132d73d322ee5d6d648f02deb9f2bc19cc659/Sources/GoTrue/Internal/SessionManager.swift#L41C18-L41C18

```
  func session() async throws -> Session {
    if let task = task {
      return try await task.value
    }

    guard let currentSession = try Env.localStorage.getSession() else {
      throw GoTrueError.sessionNotFound
    }

    if currentSession.isValid {
      return currentSession.session
    }

/////////// REFRESHING HERE ///////////
    task = Task {
      defer { self.task = nil }

      let session = try await Env.sessionRefresher(currentSession.session.refreshToken)
      try update(session)
      return session
    }

    return try await task!.value
  }
```

**Comment by kurtguenther** [comment]
After some investigation, [this](https://github.com/supabase-community/gotrue-swift/pull/55) is what was causing the erroneous 401 for me (I had kept testing the JWT during the minute where this would have been incorrectly marked as `isValid` when it was already expired).

So it should be fixed as of PR 55 for `GoTrue`

**Comment by grsouza** [comment]
Closing this issue as it seems to be solved, if it happens again, we can re-open it.

Thank you all for the investigation.

**Comment by bstillitano** [comment]
I'm getting this issue still when making requests using Postgres. Are we meant to manually update the token on the clients?

![Simulator Screenshot - iPhone 15 Pro - 2024-04-05 at 23 51 07](https://github.com/supabase-community/supabase-swift/assets/40552246/b286e8de-b7a9-44cb-8b02-0c24fd66b447)

**Comment by grdsdev** [comment]
Hi @bstillitano  shouldn't need to manually refresh.

I'll reopen this issue to investigate, thanks.

**Comment by bstillitano** [comment]
No probs @grdsdev let me know if I can help in any way.

**Comment by florian-mlr** [comment]
Same issue here, is there any news ?

**Comment by grdsdev** [comment]
@bstillitano and @florian-mlr 

Are you using PostgresClient directly, or through the SupabaseClient?

**Comment by bstillitano** [comment]
> @bstillitano and @florian-mlr 
> 
> Are you using PostgresClient directly, or through the SupabaseClient?

@grdsdev Suppose client only

**Comment by junaama** [comment]
Also experiencing the same issue, is there an update on the way?
